// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} unityWidgetName
 * @param {string} eventName
 * @param {Nanoflow} onEventHandler
 * @param {MxObject} helpContext
 * @returns {Promise.<void>}
 */
export async function ListenUnity(unityWidgetName, eventName, onEventHandler, helpContext) {
	// BEGIN USER CODE
	const instance = unityContext[unityWidgetName];
	console.log('listen ' + eventName + '@'+unityWidgetName);
	instance.on(eventName, msg => {
		onEventHandler({Msg: msg, Entity: helpContext});
	});
	// END USER CODE
}
